#| Exercise 1.9
 | Each of the following two procedures defines a method for adding two 
 | positive integers in terms of the procedures inc, which increments its 
 | argument by 1, and dec, which decrements its argument by 1.
 |
 |     (define (+ a b)
 |       (if (= a 0) b (inc (+ (dec a) b))))
 |
 |     (define (+ a b)
 |       (if (= a 0) b (+ (dec a) (inc b))))
 |
 | Using the substitution model, illustrate the process generated by each 
 | procedure in evaluating (+ 4 5). Are these processes iterative or 
 | recursive?
 |
 | Answer: Using the subsittion model for each definition, the processes 
 | generated are as follows:
 |
 |     (define (+ a b)
 |       (if (= a 0) b (inc (+ (dec a) b))))
 |
 |     > (+ 4 2)
 |     = (inc (+ (dec 4) 2))
 |     = (inc (+ 3 2))
 |     = (inc (inc (+ (dec 3) 2)))
 |     = (inc (inc (+ 2 2)))
 |     = (inc (inc (inc (+ (dec 2) 2))))
 |     = (inc (inc (inc (+ 1 2))))
 |     = (inc (inc (inc (inc (+ (dec 1) 2)))))
 |     = (inc (inc (inc (inc (+ 0 2)))))
 |     = (inc (inc (inc (inc 2)))
 |     = (inc (inc (inc 3)))
 |     = (inc (inc 4))
 |     = (inc 5)
 |     = 6
 |
 |    (define (+ a b)
 |       (if (= a 0) b (+ (dec a) (inc b))))
 |
 |     > (+ 4 2)
 |     = (+ (dec 4) (inc 2))
 |     = (+ 3 3)
 |     = (+ (dec 3) (inc 3))
 |     = (+ 2 4)
 |     = (+ (dec 2) (inc 4))
 |     = (+ 1 5)
 |     = (+ (dec 1) (inc 5))
 |     = (+ 0 6)
 |     = 6
 |
 | The first process is a recursive process since it generates a chain of  
 | deferred inc operations. The second process is linear iterative as 
 | arguments of the procedure and be evaluated immediately after application
 | of the procedure.
 |
 |#